=== hooxSoftware/TcTestframework/src/Script/Schema/FrameworkLasal.xsd
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<xs:schema xmlns:Hardware="http://hoox.software/Sigmatek" 
           xmlns:identifier="http://hoox.software/Identifier" 
           xmlns="http://hoox.software" 
           xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           targetNamespace="http://hoox.software" 
           elementFormDefault="qualified">
           
    <xs:import schemaLocation="Hardware/Sigmatek.xsd" namespace="http://hoox.software/Sigmatek"></xs:import>
    <xs:import schemaLocation="Identifier.xsd" namespace="http://hoox.software/Identifier"></xs:import>
    
    <xs:element name="Framework">
        <xs:complexType>
            <xs:sequence minOccurs="1" maxOccurs="1">
                <!-- Allgemeine Daten zur Erstellung des Applikationsprojekts -->
                <xs:element name="Project" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:attribute name="Name" type="Project_t" use="required"></xs:attribute>
                    </xs:complexType>
                </xs:element>
                <!-- Beschreibung der Hardwarekonfiguration -->
                <xs:element name="Hardware" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence minOccurs="1" maxOccurs="1">
                            <xs:element name="Device" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="IoElement" type="IoElement_t" minOccurs="1" maxOccurs="unbounded"></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Junction" type="Junction_t" minOccurs="0" maxOccurs="unbounded"></xs:element>
                            <xs:element name="Safety" type="Safety_t" minOccurs="0" maxOccurs="1"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="Disabled" type="xs:boolean" default="false"></xs:attribute>
                    </xs:complexType>
                </xs:element>
				
                <!-- Beschreibung der Softwarekonfiguration -->
                <xs:element name="Software" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
							<xs:element name="Modul" type="Modul_t" minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
					<xs:unique name="ModulName">
						<xs:selector xpath="Modul"></xs:selector>
						<xs:field xpath="@Name"></xs:field>
					</xs:unique>
					<xs:unique name="ModulId">
						<xs:selector xpath="Modul"></xs:selector>
						<xs:field xpath="@Id"></xs:field>
					</xs:unique>
                </xs:element>

                <!-- Beschreibung der Softwarekonfiguration -->
                <xs:element name="Unittest" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="TestSuite" type="TestSuite_t" minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>		
				
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!-- Typdefinitionen -->
    <xs:simpleType name="Project_t">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z0-9_]*"></xs:pattern>
            <xs:minLength value="0"></xs:minLength>
        </xs:restriction>
    </xs:simpleType>
    <!-- 1. Hardwarespezifisch -->
    <xs:complexType name="IoElement_t">
		<xs:sequence>
			<xs:element name="Channel" type ="Channel_t" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
        <xs:attribute name="Typ" type="Hardware:Hardware_t"></xs:attribute>
        <xs:attribute name="Bmk" type="Bmk_t"></xs:attribute>
        <xs:attribute name="Port1" type="Bmk_t"></xs:attribute>
        <xs:attribute name="Port2" type="Bmk_t"></xs:attribute>
        <xs:attribute name="Disabled" type="xs:boolean" default="false"></xs:attribute>
    </xs:complexType>
	
    <xs:complexType name="Channel_t">
        <xs:sequence>
            <xs:element name="Name" type="xs:string"></xs:element>
            <xs:element name="Bmk" type="Bmk_t"></xs:element>
            <xs:choice maxOccurs="1" minOccurs="1">
                <xs:element name="Input" type="identifier:Input_t"></xs:element>
                <xs:element name="Output" type="identifier:Output_t"></xs:element>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>
	
    <xs:complexType name="Junction_t">
        <xs:sequence>
            <xs:element name="IoElement" type="IoElement_t" minOccurs="0" maxOccurs="unbounded"></xs:element>
        </xs:sequence>
        <xs:attribute name="Bmk" type="Bmk_t"></xs:attribute>
    </xs:complexType>
	
    <xs:simpleType name="Bmk_t">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z0-9_]*"></xs:pattern>
            <xs:minLength value="0"></xs:minLength>
        </xs:restriction>
    </xs:simpleType>
	
    <xs:complexType name="Safety_t">
        <xs:sequence>
            <xs:element name="Channel" type="Channel_t" minOccurs="0" maxOccurs="unbounded"></xs:element>
        </xs:sequence>
    </xs:complexType>

	<xs:complexType name="Modul_t">
		<xs:attribute name="Name" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="Typ" type="identifier:Functionblock_t" use="required"></xs:attribute>
		<xs:attribute name="Id" type="identifier:Module_t" use="optional"></xs:attribute>	
	</xs:complexType>

	<xs:complexType name="TestSuite_t">
		<xs:sequence>
			<xs:element name="Test" type="Test_t" minOccurs="0" maxOccurs="unbounded"></xs:element>
		</xs:sequence>
		<xs:attribute name="Name" type="xs:string"></xs:attribute>
		<xs:attribute name="Id" type="xs:string"></xs:attribute>
	</xs:complexType>	
	
	<xs:complexType name="Test_t">
		<xs:attribute name="Name" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="Typ" type="identifier:Functionblock_t" use="required"></xs:attribute>
		<xs:attribute name="Id" type="xs:string" use="required"></xs:attribute>
	</xs:complexType>
	
</xs:schema>

=== hooxSoftware/TcTestframework/src/Script/XML/CP112_70A2.xml
<?xml version="1.0" encoding="utf-8"?>

<Framework	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xmlns="http://hoox.software"
			xmlns:Hardware="http://hoox.software/Sigmatek" 
			xsi:schemaLocation="http://hoox.software ../Schema/FrameworkLasal.xsd">

	<Project Name="CP112_70A2" />

	<Hardware Disabled="false">
		<!-- 1. Master direkt am der CPU -->
		<Device>
			<IoElement Typ="TS041" Bmk="A1100"/>
			<IoElement Typ="ST151" Bmk="A1101"/>
			<IoElement Typ="DM161" Bmk="A1200">
                 <Channel>
                     <Name/>
                     <Bmk/>
                     <Input/>
                 </Channel>
    			 <Channel>
    			     <Name>Eingang</Name>
    			     <Bmk>_1S01</Bmk>
    			     <Input>eCustom01</Input>
    			 </Channel>
    			 <Channel>
                     <Name>Ausgang</Name>
                     <Bmk>_1K01</Bmk>
                     <Output>eCustom01</Output>
                 </Channel>
	        </IoElement>
			<IoElement Typ="AI043" Bmk="A1201">
    			 <Channel>
                     <Name>Analog1</Name>
                     <Bmk>_1B01</Bmk>
                     <Input>eCustom02</Input>
                 </Channel>
                 <Channel>
                     <Name>Analog2</Name>
                     <Bmk>_1B02</Bmk>
                     <Input>eCustom03</Input>
                 </Channel>
            </IoElement>
			<IoElement Typ="DI200" Bmk="A1202"/>
			<IoElement Typ="TO161" Bmk="A1203">
			     <Channel>
                     <Name>Ausgang</Name>
                     <Bmk>_2K01</Bmk>
                     <Output>eCustom02</Output>
                 </Channel>
                 <Channel>
                     <Name>Ausgang</Name>
                     <Bmk>_2K02</Bmk>
                     <Output>eCustom03</Output>
                 </Channel>
                 <Channel>
                     <Name>Ausgang</Name>
                     <Bmk>_2K03</Bmk>
                     <Output>eCustom04</Output>
                 </Channel>                                  
			</IoElement>
			<IoElement Typ="DI200" Bmk="A1204"/>
		</Device>

	</Hardware>

	<Software>
		<Modul Name="IoCopy1"      Typ="CIoCopy"        />
	</Software>

	<Unittest>
		<TestSuite Name="TS1" Id="TS1.1">
			<Test Name="IoCopy1"      Typ="CIoCopy"   Id="TF1.6"     />
			<Test Name="IoCopy1"      Typ="CIoCopy"   Id="TF2.6"     />
			<Test Name="IoCopy1"      Typ="CIoCopy"   Id="TF3.6"     />
			<Test Name="IoCopy1"      Typ="CIoCopy"   Id="TF4.6"     />
			<Test Name="IoCopy1"      Typ="CIoCopy"   Id="TF5.6"     />			
		</TestSuite>
		
		<TestSuite Name="TS2" Id="TS1.2">
			<Test Name="IoCopy1"      Typ="CIoCopy"   Id="TF6.6"     />
			<Test Name="IoCopy1"      Typ="CIoCopy"   Id="TF7.6"     />
			<Test Name="IoCopy1"      Typ="CIoCopy"   Id="TF8.6"     />
			<Test Name="IoCopy1"      Typ="CIoCopy"   Id="TF9.6"     />
			<Test Name="IoCopy1"      Typ="CIoCopy"   Id="TF10.6"     />			
		</TestSuite>
		
	</Unittest>
	
</Framework>

<!-- Liste aller möglichen Module
	
	# Name : Name der Instanz 
	# Typ  : Name des Funktionsblocktyps (Frameworkmodul)
	# Id   : Bei Mehrfachinstanzierung notwendige ID
	         Nur bei Bausteinen die dies unterstützen notwendig
	
	<Modul Name="Lauflicht" Typ="FB_DemoLauflicht" Id=""/>
	<Modul Name="Pumpe" Typ="FB_DemoPumpe" Id=""/>
	<Modul Name="EventTest" Typ="FB_EventTest" Id=""/>

-->
